object FormBG: TFormBG
  Left = 0
  Top = 0
  AlphaBlend = True
  AlphaBlendValue = 160
  BorderStyle = bsNone
  Caption = 'FormBG'
  ClientHeight = 240
  ClientWidth = 463
  Color = clBackground
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'Tahoma'
  Font.Style = []
  OldCreateOrder = False
  OnShow = FormShow
  PixelsPerInch = 96
  TextHeight = 13
end
